all:
	gcc -m32 -g -fno-stack-protector -O0 -no-pie -static -o vegas1 vegas1.c
	gcc -m32 -g -fno-stack-protector -O0 -no-pie -static -o vegas2 vegas2.c
	gcc -m32 -g -fno-stack-protector -O0 -no-pie -static -o vegas3 vegas3.c

clean:
	rm -f vegas1 vegas2 vegas3
